[project]
name = 'CP-contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.IP-audit]
path = 'contracts/IP-audit.clar'
clarity_version = 3
epoch = 3.0

[contracts.IP-ownership]
path = 'contracts/IP-ownership.clar'
clarity_version = 3
epoch = 3.0

[contracts.ip-stamping]
path = 'contracts/ip-stamping.clar'
clarity_version = 2
epoch = 2.5

[contracts.nft-contract]
path = 'contracts/nft-contract.clar'
clarity_version = 2
epoch = 2.5

[contracts.royalty-distribution]
path = 'contracts/royalty-distribution.clar'
clarity_version = 1
epoch = 2.05
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
